name: 'Idea'
description: 'Suggest an idea for this project'
labels: enhancement
body:
  - type: textarea
    id: formulation
    attributes:
      label: Is your feature request related to a real-world problem?
      description: A clear and concise description of what the problem is and the solution you'd like
      placeholder: |
        I had a situation, when [...]
    validations:
      required: true
  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our __Contributing Guidelines__ and __Code of Conduct__
      options:
        - label: I agree to follow this project's [__Contributing Guidelines__](https://github.com/hexalang/.github/blob/kawaii/CONTRIBUTING.md)
          required: true
        - label: I agree to follow this project's [__Code of Conduct__](https://github.com/hexalang/.github/blob/kawaii/CODE_OF_CONDUCT.md)
          required: true
