// Generated by Hexa https://hexalang.github.io
// normalizer
// LICENSE LGPL-3.0-only

;(function() {
	"use strict"
	const $global = typeof(window) === "undefined"? global : window
	if (typeof($global.require) === "undefined") { $global.require = function () {} };
	var console_331 = $global.console
	function hasOwnProperty(object, name) { return object.hasOwnProperty(name) };
	function btoa(text_520) { return Buffer.from(text_520, 'binary').toString('base64') };
	function atob(base64) { return Buffer.from(base64, 'base64').toString('binary') };
	{
		{
			console.log('Thank you for choosing Hexa');
			console.log('abc' + 'dce');
			console.log('abc' + 123);
			console.log('' + (1 + 2));
			console.log('' + ('' + 2));
			console.log('' + (0.5 + 0.2));
		}
	}
})();
