// Generated by Hexa https://hexalang.github.io
// normalizer
// LICENSE LGPL-3.0-only
;(() => {
	"use strict"
	const $global = typeof(window) === "undefined"? global : window
	if (typeof($global.require) === "undefined") { $global.require = () => {} };
	const selfVersion="1.0.0";
	var NiceExpression = {
	}
	Object.defineProperty(NiceExpression, "Other", { get: () => { return [0] }})
	var console_46 = $global.console
	var EasE = class {
		constructor(value_128) {};
	}
	var AutoKeep = class {
		constructor() {};
	}
	var $Renamed = class {
		constructor() { 
			this.$renames = '123'
		{
		} };
		$ren() { return '123' };
	}
	$Renamed.$rename = '123'
	$Renamed.$renamed = () => { return '123' };
	function hasOwnProperty(object, name) { return object.hasOwnProperty(name) };
	function btoa(text_112) { return Buffer.from(text_112, 'binary').toString('base64') };
	function atob(base64) { return Buffer.from(base64, 'base64').toString('binary') };
	function $renamed() { return '123' };
	var value = 'hello'
	var another = 'hello'
	var boolean = true
	var $rename = 123
	{
		{
			console.log('Thank you for choosing Hexa');
			console.log('abcdce');
			console.log('abcdcefff');
			console.log('abc123');
			console.log('3');
			console.log('2');
			console.log('0.7');
			console.log('hello');
			console.log('xhelloy');
			console.log('xhelloy');
			{
				const nested = 'hi';
				{
					console.log('xhiy');
				};
			};
			{
				const bool = true;
				const bool_113 = true;
				const bool_114 = false;
				const bool_115 = false;
				const bool_116 = true;
				const bool_117 = true;
				console.log('xtruey');
				console.log('x' + true + 'y');
				const bool_118 = true == true;
				console.log('x' + bool_118);
				const bool_119 = false;
				const bool_120 = false;
				console.log('false == false');
				const bool_121 = true;
				const bool_122 = true;
				console.log('true == true');
				const bool_123 = false;
				const bool_124 = false;
				console.log('false == false');
				const bool_125 = true;
				const bool_126 = true;
				console.log('true == true');
				console.log('true == true');
				console.log('true == true');
			};
			{
				let i = 0;
				i++;
				{
					i++;
				};
				i--;
				{
					i--;
				};
				{
				};
				const bool_127 = () => { return false };
			};
			{
				const temp = new EasE();
				const temp_129 = new EasE(123);
			};
			{
				{
					const temp_130 = 123;
					switch (temp_130) {
					default: 
					console.log('hi')
					};
				};
				{
					const temp_131 = 123;
					switch (temp_131) {
					case 123: {
						console.log('123')
					} break;
					
					default: 
					console.log('case _: is ok at any position')
					};
				};
				{
					const temp_132 = 123;
					switch (temp_132) {
					case 123: {
						console.log('123')
					} break;
					
					default: 
					console.log('case _: is ok at any position')
					};
				};
			};
			{
				const temp_133 = new AutoKeep();
			};
			{
				const r = new $Renamed();
				console.log(r.$renames);
				console.log(r.$ren());
				console.log($Renamed.$rename);
				console.log($Renamed.$renamed());
				console.log($rename);
				console.log($renamed());
				const $local = () => { return '123' };
				console.log($local());
			};
			{
				const x = 3;
				const x_134 = 50 == 50;
			};
			{
				const expression = /*Other*/[0];
				{
					const temp_135 = expression;
					switch (temp_135&&temp_135[0]) {
					case 0: {
						console.log('Other')
					} break;
					};
				};
				{
					const temp_136 = (expression);
					switch (temp_136&&temp_136[0]) {
					case 0: {
						console.log('Other')
					} break;
					};
				};
			};
		}
	}
})();
