name: Building

on:
  push:
    branches: [ kawaii ]
  pull_request:
    branches: [ kawaii ]

jobs:
  build-windows:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run npm
      run: |
        npm ci
        npm install nexe

    - name: Build Hexa
      run: |
        node bootstrap.js hexa.json
        ./node_modules/.bin/nexe hexa-node.js --target windows-x64-14.15.3 --name hexa -o hexa

    - name: Move build results
      run: |
        mkdir out
        move hexa-node.js out\hexa-node.js
        move hexa.exe out\hexa.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out/
