name: Building

on:
  push:
    branches:
      - '**' # Matches every branch
  pull_request:
    branches:
      - kawaii # Targets the main branch

jobs:
  build-windows:
    # use oldest available to check build regressions
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: .github/workflows/building.json

    - name: Run npm
      run: |
        npm ci
        npm install nexe@4.0.0-beta.19

    - name: Build Hexa
      run: |
        node bootstrap.js hexa.json
        ./node_modules/.bin/nexe hexa-node.js --target windows-x64-14.15.3 --name hexa -o hexa

    - name: Move build results
      run: |
        mkdir out
        move hexa-node.js out\hexa-node.js
        move hexa.exe out\hexa.exe

    - name: Upload Nexe artifact
      uses: actions/upload-artifact@v3
      with:
        name: nexe
        path: out/hexa.exe

    - name: Upload Node.js artifact
      uses: actions/upload-artifact@v3
      with:
        name: hexa-node.js
        path: out/hexa-node.js
